modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="riskofrainmod" #mandatory
version="1.0" #mandatory
displayName="Risk of Rain Mod" #mandatory
logoFile="logo.png" #optional
credits="Thanks everyone who supports the effort and HOPOO GAMES for providing us with such a universe."
authors="Colo Champre" #optional
description='''
This mod brings some content from the Risk of Rain universe into Minecraft!
'''

