modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory

modId="riskofrain_items"
version="1.0" #mandatory
displayName="Risk of Rain Items"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java"
authors="Love, Cheese and small house plants"


description='''

'''

